GET http://localhost:8000/subscribers

###
GET http://localhost:8000/subscribers/6108031e92a5f3c73d048b29

###
POST http://localhost:8000/subscribers/
Content-Type: application/json

{
    "username":"Amazing2",
    "email": "SomeEmail@gmail.com",
    "password": "boo1234"
}

###
DELETE  http://localhost:8000/subscribers/61079798399d91fb5d357a6b


###
PATCH   http://localhost:8000/subscribers/6107a8ecc441aa1807623a73
Content-Type: application/json

{
    "name":"bombaya"
}
